/**
 * AstroLens API Service
 * Wraps all calls to the FastAPI backend.
 */

import { generateCosmicBlueprint } from '../utils/blueprintEngine';

// In production, VITE_API_URL should point to your Railway/Render backend.
// In development, the Vite proxy handles /api -> localhost:8000.
const BASE_URL = import.meta.env.VITE_API_URL
  ? import.meta.env.VITE_API_URL.replace(/\/$/, '')
  : '';

/**
 * Send a base64-encoded image frame to the palm scan endpoint.
 * @param {string} base64Image - data-URL or raw base64 string from the webcam.
 * @param {boolean} debug      - Request the ROI debug overlay image.
 * @returns {Promise<object>}  - Parsed JSON response from the backend.
 */
export async function scanPalm(base64Image, debug = false) {
  const response = await fetch(`${BASE_URL}/api/scan`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ image: base64Image, debug }),
  });

  if (!response.ok) {
    const error = await response.json().catch(() => ({ detail: 'Unknown error' }));
    throw new Error(error.detail || `HTTP ${response.status}`);
  }

  return response.json();
}

/**
 * Fetch a pre-baked demo reading (no image required).
 * @returns {Promise<object>}
 */
export async function getDemoReading() {
  const response = await fetch(`${BASE_URL}/api/demo`);
  if (!response.ok) throw new Error(`HTTP ${response.status}`);
  return response.json();
}

/**
 * Fetch a LIVE Cosmic Oracle reading for one category, generated by Gemini
 * from the user's real (or fallback) palm line scores.
 * @param {string} category - one of: love | career | money | direction | week
 * @param {{life:number, head:number, heart:number}} scores - 0-1 line scores
 * @param {string} [archetypeName]
 * @returns {Promise<{category:string, reading:string, source:string}>}
 */
export async function getOracleReading(category, scores, archetypeName) {
  const response = await fetch(`${BASE_URL}/api/oracle`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      category,
      life_score: scores.life,
      head_score: scores.head,
      heart_score: scores.heart,
      archetype_name: archetypeName || null,
    }),
  });

  if (!response.ok) {
    const error = await response.json().catch(() => ({ detail: 'Unknown error' }));
    throw new Error(error.detail || `HTTP ${response.status}`);
  }

  return response.json();
}

/**
 * Fetches AI-synthesized 12-section Cosmic Blueprint with Key Pattern (Phase 5B).
 * If Gemini backend is offline or fails, falls back seamlessly to deterministic blueprintEngine.js.
 *
 * @param {object} readingData - Palm reading data
 * @returns {Promise<object>} Full structured 12-section Blueprint with Key Pattern
 */
export async function getBlueprintData(readingData) {
  const fallback = generateCosmicBlueprint(readingData);

  try {
    const payload = {
      name: (readingData?.name || 'Seeker').trim(),
      archetype: readingData?.archetype_name || readingData?.archetype || 'Gold Luminary',
      aura_score: readingData?.aura_score ?? readingData?.auraScore ?? 78,
      aura_color: readingData?.aura_color || readingData?.auraColor || '#FDE68A',
      lucky_element: readingData?.lucky_element || readingData?.luckyElement || 'Fire',
      life_score: readingData?.life?.score ?? readingData?.life_score ?? 0.8,
      head_score: readingData?.head?.score ?? readingData?.head_score ?? 0.72,
      heart_score: readingData?.heart?.score ?? readingData?.heart_score ?? 0.68,
      reading: readingData?.reading || '',
      career_insight: readingData?.career_insight || '',
      energy_insight: readingData?.energy_insight || '',
    };

    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 12000);

    const response = await fetch(`${BASE_URL}/api/blueprint`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
      signal: controller.signal,
    });

    clearTimeout(timeoutId);

    if (response.ok) {
      const data = await response.json();
      if (data.source === 'gemini' && Array.isArray(data.sections) && data.sections.length === 12) {
        return {
          source: 'gemini',
          meta: fallback.meta,
          sections: data.sections,
          keyPattern: data.keyPattern || fallback.keyPattern,
          astroliveReason: data.astroliveReason || fallback.astroliveReason,
          astrologerSpecialty: data.astrologerSpecialty || fallback.astrologerSpecialty,
        };
      }
    }
  } catch (err) {
    console.info('[api] AI blueprint backend unavailable, using signature reading fallback:', err.message);
  }

  return fallback;
}


